[[topnav]]
  identifier = "quickstart"
  name = "Quickstart"
  url = "/quickstart"
  weight = 1

[[topnav]]
  identifier = "docs"
  name = "Documentation"
  url = "/docs"
  weight = 2

[[topnav]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 3

[[topnav]]
  identifier = "faq"
  name = "FAQ"
  url = "/faq"
  weight = 4

[[topnav]]
  identifier = "community"
  name = "Community"
  url = "/community"
  weight = 5

[[topnav]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 6
