baseURL: "https://syndesis.io/"
languageCode: "en-gb"
title: "Syndesis - Open source integration platform"
theme: "syndesis"
canonifyURLs: true
googleAnalytics: "UA-98663114-1"
metaDataFormat: "yaml"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: github
staticDir:
- static
- documentation
markup:
  defaultMarkdownHandler: blackfriday
  blackFriday:
    hrefTargetBlank: true
    noreferrerLinks: true
